/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.26.1
 * source: api/common/c_entry.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./c_device";
import * as dependency_2 from "./../../google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export namespace api.common {
    export enum TransportType {
        TRANSPORT_HTTP = 0,
        TRANSPORT_HTTPS = 3,
        TRANSPORT_H2C = 5,
        TRANSPORT_HTTP3 = 30
    }
    export enum AddressType {
        ADDRES_DOMAIN = 0,
        ADDRES_IPV4 = 1,
        addres_ipv6 = 2
    }
}
