/**
 * Generated by the protoc-gen-ts.  DO NOT EDIT!
 * compiler version: 5.26.1
 * source: api/common/c_worker.proto
 * git: https://github.com/thesayyn/protoc-gen-ts */
import * as dependency_1 from "./c_base";
import * as dependency_2 from "./../../validate/validate";
import * as dependency_3 from "./../../google/protobuf/timestamp";
import * as pb_1 from "google-protobuf";
export namespace api.common {
    export enum DistributionType {
        DISTRIBUTION_LEISURE = 0,
        DISTRIBUTION_BUSY = 1,
        DISTRIBUTION_OFFLINE = 2,
        DISTRIBUTION_NOT_LOGIN = 3
    }
    export enum WorkerPermission {
        WORKER_PERM_NONE = 0,
        WORKER_PERM_TOP = 1,
        WORKER_PERM_ADMIN = 2,
        WORKER_PERM_LEADER = 4,
        WORKER_PERM_FRONTER = 8,
        WORKER_PERM_TRANSFER = 16,
        WORKER_PERM_SEARCHER = 32,
        WORKER_PERM_BLACKER = 64
    }
    export enum ConnectState {
        CONNECT_STATE_OFFLINE = 0,
        CONNECT_STATE_ONLINE = 1
    }
    export enum OnlineState {
        ONLINE_STATE_IDLE = 0,
        ONLINE_STATE_BUSY = 1,
        ONLINE_STATE_AFK = 2
    }
    export enum WorkerState {
        WORKER_OFFLINE = 0,
        WORKER_READY = 1,
        WORKER_BUSY = 2,
        WORKER_LOST = 3
    }
    export enum WorkerEventType {
        WORKER_EVENT_ONLINE = 0,
        WORKER_EVENT_PING = 1,
        WORKER_EVENT_ERROR = 2,
        WORKER_EVENT_AWAY = 3,
        WORKER_EVENT_BUSY = 4,
        WORKER_EVENT_LOGOUT = 5
    }
    export class WorkerEvent extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            tenant_id?: number;
            worker_id?: number;
            socket_id?: number;
            gateway_id?: number;
            event_type?: WorkerEventType;
            event_code?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
                if ("worker_id" in data && data.worker_id != undefined) {
                    this.worker_id = data.worker_id;
                }
                if ("socket_id" in data && data.socket_id != undefined) {
                    this.socket_id = data.socket_id;
                }
                if ("gateway_id" in data && data.gateway_id != undefined) {
                    this.gateway_id = data.gateway_id;
                }
                if ("event_type" in data && data.event_type != undefined) {
                    this.event_type = data.event_type;
                }
                if ("event_code" in data && data.event_code != undefined) {
                    this.event_code = data.event_code;
                }
            }
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set tenant_id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get worker_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set worker_id(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get socket_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set socket_id(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get gateway_id() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set gateway_id(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get event_type() {
            return pb_1.Message.getFieldWithDefault(this, 4, WorkerEventType.WORKER_EVENT_ONLINE) as WorkerEventType;
        }
        set event_type(value: WorkerEventType) {
            pb_1.Message.setField(this, 4, value);
        }
        get event_code() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set event_code(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        static fromObject(data: {
            tenant_id?: number;
            worker_id?: number;
            socket_id?: number;
            gateway_id?: number;
            event_type?: WorkerEventType;
            event_code?: number;
        }): WorkerEvent {
            const message = new WorkerEvent({});
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            if (data.worker_id != null) {
                message.worker_id = data.worker_id;
            }
            if (data.socket_id != null) {
                message.socket_id = data.socket_id;
            }
            if (data.gateway_id != null) {
                message.gateway_id = data.gateway_id;
            }
            if (data.event_type != null) {
                message.event_type = data.event_type;
            }
            if (data.event_code != null) {
                message.event_code = data.event_code;
            }
            return message;
        }
        toObject() {
            const data: {
                tenant_id?: number;
                worker_id?: number;
                socket_id?: number;
                gateway_id?: number;
                event_type?: WorkerEventType;
                event_code?: number;
            } = {};
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            if (this.worker_id != null) {
                data.worker_id = this.worker_id;
            }
            if (this.socket_id != null) {
                data.socket_id = this.socket_id;
            }
            if (this.gateway_id != null) {
                data.gateway_id = this.gateway_id;
            }
            if (this.event_type != null) {
                data.event_type = this.event_type;
            }
            if (this.event_code != null) {
                data.event_code = this.event_code;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.tenant_id != 0)
                writer.writeInt32(1, this.tenant_id);
            if (this.worker_id != 0)
                writer.writeInt32(2, this.worker_id);
            if (this.socket_id != 0)
                writer.writeUint64(3, this.socket_id);
            if (this.gateway_id != 0)
                writer.writeInt32(6, this.gateway_id);
            if (this.event_type != WorkerEventType.WORKER_EVENT_ONLINE)
                writer.writeEnum(4, this.event_type);
            if (this.event_code != 0)
                writer.writeInt32(5, this.event_code);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): WorkerEvent {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new WorkerEvent();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.tenant_id = reader.readInt32();
                        break;
                    case 2:
                        message.worker_id = reader.readInt32();
                        break;
                    case 3:
                        message.socket_id = reader.readUint64();
                        break;
                    case 6:
                        message.gateway_id = reader.readInt32();
                        break;
                    case 4:
                        message.event_type = reader.readEnum();
                        break;
                    case 5:
                        message.event_code = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): WorkerEvent {
            return WorkerEvent.deserialize(bytes);
        }
    }
    export class Worker extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            worker_id?: number;
            account?: string;
            group?: WorkerGroup[];
            perm_mask?: number;
            name?: string;
            avatar?: string;
            online_state?: OnlineState;
            password?: string;
            connect_state?: ConnectState;
            tenant_id?: number;
            worker_nimid?: string;
            worker_nimsession?: string;
            bneednim?: boolean;
            group_child?: WorkerGroup[];
            tips?: string;
            consult_ids?: number[];
            delete_at?: dependency_3.google.protobuf.Timestamp;
            create_at?: dependency_3.google.protobuf.Timestamp;
            update_at?: dependency_3.google.protobuf.Timestamp;
            disable_status?: dependency_1.api.common.DisableStatus;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [3, 14, 16], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("worker_id" in data && data.worker_id != undefined) {
                    this.worker_id = data.worker_id;
                }
                if ("account" in data && data.account != undefined) {
                    this.account = data.account;
                }
                if ("group" in data && data.group != undefined) {
                    this.group = data.group;
                }
                if ("perm_mask" in data && data.perm_mask != undefined) {
                    this.perm_mask = data.perm_mask;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("avatar" in data && data.avatar != undefined) {
                    this.avatar = data.avatar;
                }
                if ("online_state" in data && data.online_state != undefined) {
                    this.online_state = data.online_state;
                }
                if ("password" in data && data.password != undefined) {
                    this.password = data.password;
                }
                if ("connect_state" in data && data.connect_state != undefined) {
                    this.connect_state = data.connect_state;
                }
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
                if ("worker_nimid" in data && data.worker_nimid != undefined) {
                    this.worker_nimid = data.worker_nimid;
                }
                if ("worker_nimsession" in data && data.worker_nimsession != undefined) {
                    this.worker_nimsession = data.worker_nimsession;
                }
                if ("bneednim" in data && data.bneednim != undefined) {
                    this.bneednim = data.bneednim;
                }
                if ("group_child" in data && data.group_child != undefined) {
                    this.group_child = data.group_child;
                }
                if ("tips" in data && data.tips != undefined) {
                    this.tips = data.tips;
                }
                if ("consult_ids" in data && data.consult_ids != undefined) {
                    this.consult_ids = data.consult_ids;
                }
                if ("delete_at" in data && data.delete_at != undefined) {
                    this.delete_at = data.delete_at;
                }
                if ("create_at" in data && data.create_at != undefined) {
                    this.create_at = data.create_at;
                }
                if ("update_at" in data && data.update_at != undefined) {
                    this.update_at = data.update_at;
                }
                if ("disable_status" in data && data.disable_status != undefined) {
                    this.disable_status = data.disable_status;
                }
            }
        }
        get worker_id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set worker_id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get account() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set account(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get group() {
            return pb_1.Message.getRepeatedWrapperField(this, WorkerGroup, 3) as WorkerGroup[];
        }
        set group(value: WorkerGroup[]) {
            pb_1.Message.setRepeatedWrapperField(this, 3, value);
        }
        get perm_mask() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set perm_mask(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get avatar() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set avatar(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get online_state() {
            return pb_1.Message.getFieldWithDefault(this, 7, OnlineState.ONLINE_STATE_IDLE) as OnlineState;
        }
        set online_state(value: OnlineState) {
            pb_1.Message.setField(this, 7, value);
        }
        get password() {
            return pb_1.Message.getFieldWithDefault(this, 8, "") as string;
        }
        set password(value: string) {
            pb_1.Message.setField(this, 8, value);
        }
        get connect_state() {
            return pb_1.Message.getFieldWithDefault(this, 9, ConnectState.CONNECT_STATE_OFFLINE) as ConnectState;
        }
        set connect_state(value: ConnectState) {
            pb_1.Message.setField(this, 9, value);
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
        }
        set tenant_id(value: number) {
            pb_1.Message.setField(this, 10, value);
        }
        get worker_nimid() {
            return pb_1.Message.getFieldWithDefault(this, 11, "") as string;
        }
        set worker_nimid(value: string) {
            pb_1.Message.setField(this, 11, value);
        }
        get worker_nimsession() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set worker_nimsession(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        get bneednim() {
            return pb_1.Message.getFieldWithDefault(this, 13, false) as boolean;
        }
        set bneednim(value: boolean) {
            pb_1.Message.setField(this, 13, value);
        }
        get group_child() {
            return pb_1.Message.getRepeatedWrapperField(this, WorkerGroup, 14) as WorkerGroup[];
        }
        set group_child(value: WorkerGroup[]) {
            pb_1.Message.setRepeatedWrapperField(this, 14, value);
        }
        get tips() {
            return pb_1.Message.getFieldWithDefault(this, 15, "") as string;
        }
        set tips(value: string) {
            pb_1.Message.setField(this, 15, value);
        }
        get consult_ids() {
            return pb_1.Message.getFieldWithDefault(this, 16, []) as number[];
        }
        set consult_ids(value: number[]) {
            pb_1.Message.setField(this, 16, value);
        }
        get delete_at() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 17) as dependency_3.google.protobuf.Timestamp;
        }
        set delete_at(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 17, value);
        }
        get has_delete_at() {
            return pb_1.Message.getField(this, 17) != null;
        }
        get create_at() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 18) as dependency_3.google.protobuf.Timestamp;
        }
        set create_at(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 18, value);
        }
        get has_create_at() {
            return pb_1.Message.getField(this, 18) != null;
        }
        get update_at() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 19) as dependency_3.google.protobuf.Timestamp;
        }
        set update_at(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 19, value);
        }
        get has_update_at() {
            return pb_1.Message.getField(this, 19) != null;
        }
        get disable_status() {
            return pb_1.Message.getFieldWithDefault(this, 20, dependency_1.api.common.DisableStatus.DEFAULT) as dependency_1.api.common.DisableStatus;
        }
        set disable_status(value: dependency_1.api.common.DisableStatus) {
            pb_1.Message.setField(this, 20, value);
        }
        static fromObject(data: {
            worker_id?: number;
            account?: string;
            group?: ReturnType<typeof WorkerGroup.prototype.toObject>[];
            perm_mask?: number;
            name?: string;
            avatar?: string;
            online_state?: OnlineState;
            password?: string;
            connect_state?: ConnectState;
            tenant_id?: number;
            worker_nimid?: string;
            worker_nimsession?: string;
            bneednim?: boolean;
            group_child?: ReturnType<typeof WorkerGroup.prototype.toObject>[];
            tips?: string;
            consult_ids?: number[];
            delete_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            create_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            update_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            disable_status?: dependency_1.api.common.DisableStatus;
        }): Worker {
            const message = new Worker({});
            if (data.worker_id != null) {
                message.worker_id = data.worker_id;
            }
            if (data.account != null) {
                message.account = data.account;
            }
            if (data.group != null) {
                message.group = data.group.map(item => WorkerGroup.fromObject(item));
            }
            if (data.perm_mask != null) {
                message.perm_mask = data.perm_mask;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.avatar != null) {
                message.avatar = data.avatar;
            }
            if (data.online_state != null) {
                message.online_state = data.online_state;
            }
            if (data.password != null) {
                message.password = data.password;
            }
            if (data.connect_state != null) {
                message.connect_state = data.connect_state;
            }
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            if (data.worker_nimid != null) {
                message.worker_nimid = data.worker_nimid;
            }
            if (data.worker_nimsession != null) {
                message.worker_nimsession = data.worker_nimsession;
            }
            if (data.bneednim != null) {
                message.bneednim = data.bneednim;
            }
            if (data.group_child != null) {
                message.group_child = data.group_child.map(item => WorkerGroup.fromObject(item));
            }
            if (data.tips != null) {
                message.tips = data.tips;
            }
            if (data.consult_ids != null) {
                message.consult_ids = data.consult_ids;
            }
            if (data.delete_at != null) {
                message.delete_at = dependency_3.google.protobuf.Timestamp.fromObject(data.delete_at);
            }
            if (data.create_at != null) {
                message.create_at = dependency_3.google.protobuf.Timestamp.fromObject(data.create_at);
            }
            if (data.update_at != null) {
                message.update_at = dependency_3.google.protobuf.Timestamp.fromObject(data.update_at);
            }
            if (data.disable_status != null) {
                message.disable_status = data.disable_status;
            }
            return message;
        }
        toObject() {
            const data: {
                worker_id?: number;
                account?: string;
                group?: ReturnType<typeof WorkerGroup.prototype.toObject>[];
                perm_mask?: number;
                name?: string;
                avatar?: string;
                online_state?: OnlineState;
                password?: string;
                connect_state?: ConnectState;
                tenant_id?: number;
                worker_nimid?: string;
                worker_nimsession?: string;
                bneednim?: boolean;
                group_child?: ReturnType<typeof WorkerGroup.prototype.toObject>[];
                tips?: string;
                consult_ids?: number[];
                delete_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                create_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                update_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                disable_status?: dependency_1.api.common.DisableStatus;
            } = {};
            if (this.worker_id != null) {
                data.worker_id = this.worker_id;
            }
            if (this.account != null) {
                data.account = this.account;
            }
            if (this.group != null) {
                data.group = this.group.map((item: WorkerGroup) => item.toObject());
            }
            if (this.perm_mask != null) {
                data.perm_mask = this.perm_mask;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.avatar != null) {
                data.avatar = this.avatar;
            }
            if (this.online_state != null) {
                data.online_state = this.online_state;
            }
            if (this.password != null) {
                data.password = this.password;
            }
            if (this.connect_state != null) {
                data.connect_state = this.connect_state;
            }
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            if (this.worker_nimid != null) {
                data.worker_nimid = this.worker_nimid;
            }
            if (this.worker_nimsession != null) {
                data.worker_nimsession = this.worker_nimsession;
            }
            if (this.bneednim != null) {
                data.bneednim = this.bneednim;
            }
            if (this.group_child != null) {
                data.group_child = this.group_child.map((item: WorkerGroup) => item.toObject());
            }
            if (this.tips != null) {
                data.tips = this.tips;
            }
            if (this.consult_ids != null) {
                data.consult_ids = this.consult_ids;
            }
            if (this.delete_at != null) {
                data.delete_at = this.delete_at.toObject();
            }
            if (this.create_at != null) {
                data.create_at = this.create_at.toObject();
            }
            if (this.update_at != null) {
                data.update_at = this.update_at.toObject();
            }
            if (this.disable_status != null) {
                data.disable_status = this.disable_status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.worker_id != 0)
                writer.writeInt32(1, this.worker_id);
            if (this.account.length)
                writer.writeString(2, this.account);
            if (this.group.length)
                writer.writeRepeatedMessage(3, this.group, (item: WorkerGroup) => item.serialize(writer));
            if (this.perm_mask != 0)
                writer.writeInt32(4, this.perm_mask);
            if (this.name.length)
                writer.writeString(5, this.name);
            if (this.avatar.length)
                writer.writeString(6, this.avatar);
            if (this.online_state != OnlineState.ONLINE_STATE_IDLE)
                writer.writeEnum(7, this.online_state);
            if (this.password.length)
                writer.writeString(8, this.password);
            if (this.connect_state != ConnectState.CONNECT_STATE_OFFLINE)
                writer.writeEnum(9, this.connect_state);
            if (this.tenant_id != 0)
                writer.writeInt32(10, this.tenant_id);
            if (this.worker_nimid.length)
                writer.writeString(11, this.worker_nimid);
            if (this.worker_nimsession.length)
                writer.writeString(12, this.worker_nimsession);
            if (this.bneednim != false)
                writer.writeBool(13, this.bneednim);
            if (this.group_child.length)
                writer.writeRepeatedMessage(14, this.group_child, (item: WorkerGroup) => item.serialize(writer));
            if (this.tips.length)
                writer.writeString(15, this.tips);
            if (this.consult_ids.length)
                writer.writePackedUint32(16, this.consult_ids);
            if (this.has_delete_at)
                writer.writeMessage(17, this.delete_at, () => this.delete_at.serialize(writer));
            if (this.has_create_at)
                writer.writeMessage(18, this.create_at, () => this.create_at.serialize(writer));
            if (this.has_update_at)
                writer.writeMessage(19, this.update_at, () => this.update_at.serialize(writer));
            if (this.disable_status != dependency_1.api.common.DisableStatus.DEFAULT)
                writer.writeEnum(20, this.disable_status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Worker {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Worker();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.worker_id = reader.readInt32();
                        break;
                    case 2:
                        message.account = reader.readString();
                        break;
                    case 3:
                        reader.readMessage(message.group, () => pb_1.Message.addToRepeatedWrapperField(message, 3, WorkerGroup.deserialize(reader), WorkerGroup));
                        break;
                    case 4:
                        message.perm_mask = reader.readInt32();
                        break;
                    case 5:
                        message.name = reader.readString();
                        break;
                    case 6:
                        message.avatar = reader.readString();
                        break;
                    case 7:
                        message.online_state = reader.readEnum();
                        break;
                    case 8:
                        message.password = reader.readString();
                        break;
                    case 9:
                        message.connect_state = reader.readEnum();
                        break;
                    case 10:
                        message.tenant_id = reader.readInt32();
                        break;
                    case 11:
                        message.worker_nimid = reader.readString();
                        break;
                    case 12:
                        message.worker_nimsession = reader.readString();
                        break;
                    case 13:
                        message.bneednim = reader.readBool();
                        break;
                    case 14:
                        reader.readMessage(message.group_child, () => pb_1.Message.addToRepeatedWrapperField(message, 14, WorkerGroup.deserialize(reader), WorkerGroup));
                        break;
                    case 15:
                        message.tips = reader.readString();
                        break;
                    case 16:
                        message.consult_ids = reader.readPackedUint32();
                        break;
                    case 17:
                        reader.readMessage(message.delete_at, () => message.delete_at = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 18:
                        reader.readMessage(message.create_at, () => message.create_at = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 19:
                        reader.readMessage(message.update_at, () => message.update_at = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 20:
                        message.disable_status = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Worker {
            return Worker.deserialize(bytes);
        }
    }
    export class WorkerGroup extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            name?: string;
            priority?: number;
            count?: number;
            parentId?: number;
            ratio?: number;
            consult_id?: number;
            delete_at?: dependency_3.google.protobuf.Timestamp;
            disable_status?: dependency_1.api.common.DisableStatus;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("priority" in data && data.priority != undefined) {
                    this.priority = data.priority;
                }
                if ("count" in data && data.count != undefined) {
                    this.count = data.count;
                }
                if ("parentId" in data && data.parentId != undefined) {
                    this.parentId = data.parentId;
                }
                if ("ratio" in data && data.ratio != undefined) {
                    this.ratio = data.ratio;
                }
                if ("consult_id" in data && data.consult_id != undefined) {
                    this.consult_id = data.consult_id;
                }
                if ("delete_at" in data && data.delete_at != undefined) {
                    this.delete_at = data.delete_at;
                }
                if ("disable_status" in data && data.disable_status != undefined) {
                    this.disable_status = data.disable_status;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get priority() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set priority(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get count() {
            return pb_1.Message.getFieldWithDefault(this, 4, 0) as number;
        }
        set count(value: number) {
            pb_1.Message.setField(this, 4, value);
        }
        get parentId() {
            return pb_1.Message.getFieldWithDefault(this, 5, 0) as number;
        }
        set parentId(value: number) {
            pb_1.Message.setField(this, 5, value);
        }
        get ratio() {
            return pb_1.Message.getFieldWithDefault(this, 6, 0) as number;
        }
        set ratio(value: number) {
            pb_1.Message.setField(this, 6, value);
        }
        get consult_id() {
            return pb_1.Message.getFieldWithDefault(this, 7, 0) as number;
        }
        set consult_id(value: number) {
            pb_1.Message.setField(this, 7, value);
        }
        get delete_at() {
            return pb_1.Message.getWrapperField(this, dependency_3.google.protobuf.Timestamp, 8) as dependency_3.google.protobuf.Timestamp;
        }
        set delete_at(value: dependency_3.google.protobuf.Timestamp) {
            pb_1.Message.setWrapperField(this, 8, value);
        }
        get has_delete_at() {
            return pb_1.Message.getField(this, 8) != null;
        }
        get disable_status() {
            return pb_1.Message.getFieldWithDefault(this, 9, dependency_1.api.common.DisableStatus.DEFAULT) as dependency_1.api.common.DisableStatus;
        }
        set disable_status(value: dependency_1.api.common.DisableStatus) {
            pb_1.Message.setField(this, 9, value);
        }
        static fromObject(data: {
            id?: number;
            name?: string;
            priority?: number;
            count?: number;
            parentId?: number;
            ratio?: number;
            consult_id?: number;
            delete_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
            disable_status?: dependency_1.api.common.DisableStatus;
        }): WorkerGroup {
            const message = new WorkerGroup({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.priority != null) {
                message.priority = data.priority;
            }
            if (data.count != null) {
                message.count = data.count;
            }
            if (data.parentId != null) {
                message.parentId = data.parentId;
            }
            if (data.ratio != null) {
                message.ratio = data.ratio;
            }
            if (data.consult_id != null) {
                message.consult_id = data.consult_id;
            }
            if (data.delete_at != null) {
                message.delete_at = dependency_3.google.protobuf.Timestamp.fromObject(data.delete_at);
            }
            if (data.disable_status != null) {
                message.disable_status = data.disable_status;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                name?: string;
                priority?: number;
                count?: number;
                parentId?: number;
                ratio?: number;
                consult_id?: number;
                delete_at?: ReturnType<typeof dependency_3.google.protobuf.Timestamp.prototype.toObject>;
                disable_status?: dependency_1.api.common.DisableStatus;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.priority != null) {
                data.priority = this.priority;
            }
            if (this.count != null) {
                data.count = this.count;
            }
            if (this.parentId != null) {
                data.parentId = this.parentId;
            }
            if (this.ratio != null) {
                data.ratio = this.ratio;
            }
            if (this.consult_id != null) {
                data.consult_id = this.consult_id;
            }
            if (this.delete_at != null) {
                data.delete_at = this.delete_at.toObject();
            }
            if (this.disable_status != null) {
                data.disable_status = this.disable_status;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.name.length)
                writer.writeString(2, this.name);
            if (this.priority != 0)
                writer.writeInt32(3, this.priority);
            if (this.count != 0)
                writer.writeInt32(4, this.count);
            if (this.parentId != 0)
                writer.writeInt64(5, this.parentId);
            if (this.ratio != 0)
                writer.writeInt32(6, this.ratio);
            if (this.consult_id != 0)
                writer.writeUint32(7, this.consult_id);
            if (this.has_delete_at)
                writer.writeMessage(8, this.delete_at, () => this.delete_at.serialize(writer));
            if (this.disable_status != dependency_1.api.common.DisableStatus.DEFAULT)
                writer.writeEnum(9, this.disable_status);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): WorkerGroup {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new WorkerGroup();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.name = reader.readString();
                        break;
                    case 3:
                        message.priority = reader.readInt32();
                        break;
                    case 4:
                        message.count = reader.readInt32();
                        break;
                    case 5:
                        message.parentId = reader.readInt64();
                        break;
                    case 6:
                        message.ratio = reader.readInt32();
                        break;
                    case 7:
                        message.consult_id = reader.readUint32();
                        break;
                    case 8:
                        reader.readMessage(message.delete_at, () => message.delete_at = dependency_3.google.protobuf.Timestamp.deserialize(reader));
                        break;
                    case 9:
                        message.disable_status = reader.readEnum();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): WorkerGroup {
            return WorkerGroup.deserialize(bytes);
        }
    }
    export class Distribution extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            name?: string;
            priority?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("priority" in data && data.priority != undefined) {
                    this.priority = data.priority;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get priority() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set priority(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            id?: number;
            name?: string;
            priority?: number;
        }): Distribution {
            const message = new Distribution({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.priority != null) {
                message.priority = data.priority;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                name?: string;
                priority?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.priority != null) {
                data.priority = this.priority;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt64(1, this.id);
            if (this.name.length)
                writer.writeString(2, this.name);
            if (this.priority != 0)
                writer.writeInt32(3, this.priority);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): Distribution {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new Distribution();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt64();
                        break;
                    case 2:
                        message.name = reader.readString();
                        break;
                    case 3:
                        message.priority = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): Distribution {
            return Distribution.deserialize(bytes);
        }
    }
    export class TenantClique extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            name?: string;
            priority?: number;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("priority" in data && data.priority != undefined) {
                    this.priority = data.priority;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 2, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 2, value);
        }
        get priority() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set priority(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        static fromObject(data: {
            id?: number;
            name?: string;
            priority?: number;
        }): TenantClique {
            const message = new TenantClique({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.priority != null) {
                message.priority = data.priority;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                name?: string;
                priority?: number;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.priority != null) {
                data.priority = this.priority;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (this.name.length)
                writer.writeString(2, this.name);
            if (this.priority != 0)
                writer.writeInt32(3, this.priority);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): TenantClique {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new TenantClique();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    case 2:
                        message.name = reader.readString();
                        break;
                    case 3:
                        message.priority = reader.readInt32();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): TenantClique {
            return TenantClique.deserialize(bytes);
        }
    }
    export class ApplyWorkerState extends pb_1.Message {
        #one_of_decls: number[][] = [];
        constructor(data?: any[] | {
            id?: number;
            tenant_id?: number;
            worker_id?: number;
            name?: string;
            worker_group_name?: string;
            worker_group_child_name?: string;
            online_state_now?: OnlineState;
            online_state_apply?: OnlineState;
            apply_state?: number;
            apply_time?: number;
            check_time?: number;
            update_username?: string;
        }) {
            super();
            pb_1.Message.initialize(this, Array.isArray(data) ? data : [], 0, -1, [], this.#one_of_decls);
            if (!Array.isArray(data) && typeof data == "object") {
                if ("id" in data && data.id != undefined) {
                    this.id = data.id;
                }
                if ("tenant_id" in data && data.tenant_id != undefined) {
                    this.tenant_id = data.tenant_id;
                }
                if ("worker_id" in data && data.worker_id != undefined) {
                    this.worker_id = data.worker_id;
                }
                if ("name" in data && data.name != undefined) {
                    this.name = data.name;
                }
                if ("worker_group_name" in data && data.worker_group_name != undefined) {
                    this.worker_group_name = data.worker_group_name;
                }
                if ("worker_group_child_name" in data && data.worker_group_child_name != undefined) {
                    this.worker_group_child_name = data.worker_group_child_name;
                }
                if ("online_state_now" in data && data.online_state_now != undefined) {
                    this.online_state_now = data.online_state_now;
                }
                if ("online_state_apply" in data && data.online_state_apply != undefined) {
                    this.online_state_apply = data.online_state_apply;
                }
                if ("apply_state" in data && data.apply_state != undefined) {
                    this.apply_state = data.apply_state;
                }
                if ("apply_time" in data && data.apply_time != undefined) {
                    this.apply_time = data.apply_time;
                }
                if ("check_time" in data && data.check_time != undefined) {
                    this.check_time = data.check_time;
                }
                if ("update_username" in data && data.update_username != undefined) {
                    this.update_username = data.update_username;
                }
            }
        }
        get id() {
            return pb_1.Message.getFieldWithDefault(this, 1, 0) as number;
        }
        set id(value: number) {
            pb_1.Message.setField(this, 1, value);
        }
        get tenant_id() {
            return pb_1.Message.getFieldWithDefault(this, 2, 0) as number;
        }
        set tenant_id(value: number) {
            pb_1.Message.setField(this, 2, value);
        }
        get worker_id() {
            return pb_1.Message.getFieldWithDefault(this, 3, 0) as number;
        }
        set worker_id(value: number) {
            pb_1.Message.setField(this, 3, value);
        }
        get name() {
            return pb_1.Message.getFieldWithDefault(this, 4, "") as string;
        }
        set name(value: string) {
            pb_1.Message.setField(this, 4, value);
        }
        get worker_group_name() {
            return pb_1.Message.getFieldWithDefault(this, 5, "") as string;
        }
        set worker_group_name(value: string) {
            pb_1.Message.setField(this, 5, value);
        }
        get worker_group_child_name() {
            return pb_1.Message.getFieldWithDefault(this, 6, "") as string;
        }
        set worker_group_child_name(value: string) {
            pb_1.Message.setField(this, 6, value);
        }
        get online_state_now() {
            return pb_1.Message.getFieldWithDefault(this, 7, OnlineState.ONLINE_STATE_IDLE) as OnlineState;
        }
        set online_state_now(value: OnlineState) {
            pb_1.Message.setField(this, 7, value);
        }
        get online_state_apply() {
            return pb_1.Message.getFieldWithDefault(this, 8, OnlineState.ONLINE_STATE_IDLE) as OnlineState;
        }
        set online_state_apply(value: OnlineState) {
            pb_1.Message.setField(this, 8, value);
        }
        get apply_state() {
            return pb_1.Message.getFieldWithDefault(this, 9, 0) as number;
        }
        set apply_state(value: number) {
            pb_1.Message.setField(this, 9, value);
        }
        get apply_time() {
            return pb_1.Message.getFieldWithDefault(this, 10, 0) as number;
        }
        set apply_time(value: number) {
            pb_1.Message.setField(this, 10, value);
        }
        get check_time() {
            return pb_1.Message.getFieldWithDefault(this, 11, 0) as number;
        }
        set check_time(value: number) {
            pb_1.Message.setField(this, 11, value);
        }
        get update_username() {
            return pb_1.Message.getFieldWithDefault(this, 12, "") as string;
        }
        set update_username(value: string) {
            pb_1.Message.setField(this, 12, value);
        }
        static fromObject(data: {
            id?: number;
            tenant_id?: number;
            worker_id?: number;
            name?: string;
            worker_group_name?: string;
            worker_group_child_name?: string;
            online_state_now?: OnlineState;
            online_state_apply?: OnlineState;
            apply_state?: number;
            apply_time?: number;
            check_time?: number;
            update_username?: string;
        }): ApplyWorkerState {
            const message = new ApplyWorkerState({});
            if (data.id != null) {
                message.id = data.id;
            }
            if (data.tenant_id != null) {
                message.tenant_id = data.tenant_id;
            }
            if (data.worker_id != null) {
                message.worker_id = data.worker_id;
            }
            if (data.name != null) {
                message.name = data.name;
            }
            if (data.worker_group_name != null) {
                message.worker_group_name = data.worker_group_name;
            }
            if (data.worker_group_child_name != null) {
                message.worker_group_child_name = data.worker_group_child_name;
            }
            if (data.online_state_now != null) {
                message.online_state_now = data.online_state_now;
            }
            if (data.online_state_apply != null) {
                message.online_state_apply = data.online_state_apply;
            }
            if (data.apply_state != null) {
                message.apply_state = data.apply_state;
            }
            if (data.apply_time != null) {
                message.apply_time = data.apply_time;
            }
            if (data.check_time != null) {
                message.check_time = data.check_time;
            }
            if (data.update_username != null) {
                message.update_username = data.update_username;
            }
            return message;
        }
        toObject() {
            const data: {
                id?: number;
                tenant_id?: number;
                worker_id?: number;
                name?: string;
                worker_group_name?: string;
                worker_group_child_name?: string;
                online_state_now?: OnlineState;
                online_state_apply?: OnlineState;
                apply_state?: number;
                apply_time?: number;
                check_time?: number;
                update_username?: string;
            } = {};
            if (this.id != null) {
                data.id = this.id;
            }
            if (this.tenant_id != null) {
                data.tenant_id = this.tenant_id;
            }
            if (this.worker_id != null) {
                data.worker_id = this.worker_id;
            }
            if (this.name != null) {
                data.name = this.name;
            }
            if (this.worker_group_name != null) {
                data.worker_group_name = this.worker_group_name;
            }
            if (this.worker_group_child_name != null) {
                data.worker_group_child_name = this.worker_group_child_name;
            }
            if (this.online_state_now != null) {
                data.online_state_now = this.online_state_now;
            }
            if (this.online_state_apply != null) {
                data.online_state_apply = this.online_state_apply;
            }
            if (this.apply_state != null) {
                data.apply_state = this.apply_state;
            }
            if (this.apply_time != null) {
                data.apply_time = this.apply_time;
            }
            if (this.check_time != null) {
                data.check_time = this.check_time;
            }
            if (this.update_username != null) {
                data.update_username = this.update_username;
            }
            return data;
        }
        serialize(): Uint8Array;
        serialize(w: pb_1.BinaryWriter): void;
        serialize(w?: pb_1.BinaryWriter): Uint8Array | void {
            const writer = w || new pb_1.BinaryWriter();
            if (this.id != 0)
                writer.writeInt32(1, this.id);
            if (this.tenant_id != 0)
                writer.writeInt32(2, this.tenant_id);
            if (this.worker_id != 0)
                writer.writeInt32(3, this.worker_id);
            if (this.name.length)
                writer.writeString(4, this.name);
            if (this.worker_group_name.length)
                writer.writeString(5, this.worker_group_name);
            if (this.worker_group_child_name.length)
                writer.writeString(6, this.worker_group_child_name);
            if (this.online_state_now != OnlineState.ONLINE_STATE_IDLE)
                writer.writeEnum(7, this.online_state_now);
            if (this.online_state_apply != OnlineState.ONLINE_STATE_IDLE)
                writer.writeEnum(8, this.online_state_apply);
            if (this.apply_state != 0)
                writer.writeInt32(9, this.apply_state);
            if (this.apply_time != 0)
                writer.writeInt64(10, this.apply_time);
            if (this.check_time != 0)
                writer.writeInt64(11, this.check_time);
            if (this.update_username.length)
                writer.writeString(12, this.update_username);
            if (!w)
                return writer.getResultBuffer();
        }
        static deserialize(bytes: Uint8Array | pb_1.BinaryReader): ApplyWorkerState {
            const reader = bytes instanceof pb_1.BinaryReader ? bytes : new pb_1.BinaryReader(bytes), message = new ApplyWorkerState();
            while (reader.nextField()) {
                if (reader.isEndGroup())
                    break;
                switch (reader.getFieldNumber()) {
                    case 1:
                        message.id = reader.readInt32();
                        break;
                    case 2:
                        message.tenant_id = reader.readInt32();
                        break;
                    case 3:
                        message.worker_id = reader.readInt32();
                        break;
                    case 4:
                        message.name = reader.readString();
                        break;
                    case 5:
                        message.worker_group_name = reader.readString();
                        break;
                    case 6:
                        message.worker_group_child_name = reader.readString();
                        break;
                    case 7:
                        message.online_state_now = reader.readEnum();
                        break;
                    case 8:
                        message.online_state_apply = reader.readEnum();
                        break;
                    case 9:
                        message.apply_state = reader.readInt32();
                        break;
                    case 10:
                        message.apply_time = reader.readInt64();
                        break;
                    case 11:
                        message.check_time = reader.readInt64();
                        break;
                    case 12:
                        message.update_username = reader.readString();
                        break;
                    default: reader.skipField();
                }
            }
            return message;
        }
        serializeBinary(): Uint8Array {
            return this.serialize();
        }
        static deserializeBinary(bytes: Uint8Array): ApplyWorkerState {
            return ApplyWorkerState.deserialize(bytes);
        }
    }
}
